version: '3.8'

services:
  milvus:
    image: milvusdb/milvus:v2.4.1
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    command: ["milvus", "standalone"]

  app:
    build: .
    container_name: app
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    depends_on:
      - milvus
